# Generated by Django 5.0.6 on 2024-06-26 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_productrequests'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrequests',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
